[[cupynumeric]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "574c35c143ae6bf73e35e3c198e9eaa7aba35d71"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "70fc437410b1b756e2f96ce6770480a28985fd42ac3618659608757f227b38fc"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.3+0/cupynumeric.v25.10.3.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "212832bb6e96f8b426075daee77d16a800af5c6f"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "d3c9c9d4939f11f64fe177f7cda388b932ed69e9828823833367fb9e5ab33ee3"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.3+0/cupynumeric.v25.10.3.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
