# Autogenerated wrapper script for cupynumeric_jll for x86_64-linux-gnu-cxx11-cuda+13.0
export cuda_header, libcupynumeric

using legate_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("cupynumeric")
JLLWrappers.@declare_file_product(cuda_header)
JLLWrappers.@declare_library_product(libcupynumeric, "libcupynumeric.so")
function __init__()
    JLLWrappers.@generate_init_header(legate_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_file_product(
        cuda_header,
        "include/cupynumeric/cuda/cuda.h",
    )

    JLLWrappers.@init_library_product(
        libcupynumeric,
        "lib/libcupynumeric.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
